print("Hello World")
print("This is Karthik")
print("Hi All!!! This is Panda Language aimed for the beginners")
print("Enter the number")
x = int(input())
print("Square of the number is: ")
print(x**2)
